blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('detail/', views.register, name="detail"),
    path('registrationpage/', views.registerPage, name="registrationpage"),
    path('login/', views.loginUser, name="login"),
    path('loginpage/', TemplateView.as_view(template_name="registration/login.html")),
    path('logout/', views.logout, name="logout"),
    

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class PublishedManager(models.Manager):
     def get_quary(self):
          return super(PublishedManager,
                       self).get_queryset() \
                            .filter(status='published')

class Post(models.Model):
    STATUS_CHOICE = (
         ('draft' , 'Draft'),
         ('published', 'Published')
    )

    title   = models.CharField(max_length=250)
    slug    = models.SlugField(max_length=250,unique_for_date='publish')
    author  = models.ForeignKey(User , on_delete=models.CASCADE ,related_name='blog_posts' )
    body    = models.TextField()
    publish = models.DateTimeField( default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update  = models.DateTimeField(auto_now=True)
    status  = models.CharField(max_length=10 , choices=STATUS_CHOICE,default='draft')
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
    
    class meta:
        ordering = ('-publish')

    def __str__(self):
        return self.title


class comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update  = models.DateTimeField(auto_now=True)
    active  = models.BooleanField(default=True)

    class meta:
        ordering = ('created',)

    def __str__(self):
        return 'comment by {} on {}'.format(self.name,self.post)


class signup(models.Model):
    FirstName = models.CharField(max_length=200, null=True, blank=True)
    LastName = models.CharField(max_length=200, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    Email = models.EmailField(null=True, blank=True)
    country = models.CharField(max_length=100,null=True, blank=True)
    state = models.CharField(max_length=100,null=True, blank=True)
    city = models.CharField(max_length=100,null=True, blank=True)
    pincode = models.IntegerField(null=True, blank=True)

def __str__(self):
    return str(self.id)



     

blog/forms.py
from django import forms
from .models import comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.contrib.auth import login,authenticate
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, signup
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
# Create your views here


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return render(request, 'blog/post/detail.html', {'post':post, 'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

    else:
      comment_form = CommentForm()
      return render(request, 'blog/post/detail.html', {'post':post, 'comments':comments,'new_comment':new_comment,'comment_form':comment_form})


def post_share(request, post_id):
  post = get_object_or_404(Post, id=post_id, status='published')
  sent = False

  if request.method == 'POST':
      form = EmailPostForm(request.POST)
      if form.is_valid():
          cd = form.cleaned_data
          post_url= request.build_absolute_uri(post.get_absolute_url())
          subject = '{} ({}) recommended you reading "{}"'.format(cd['name'] , cd['email'],post.title)
          message = 'Read "{}" at {}\n\n{}\'s comment:{}'.format(post.title, post_url,cd['name'],cd['comments'])
          send_mail(subject, message, 'admin@admin.com', [cd['to']])
          sent=True
  else:
    form = EmailPostForm()
  return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def home(request):
  return render(request, "blog/post/home.html")


def registerPage(request):
  return render(request, "registration/register.html")


def register(request):
    if request.method == "POST":
        FirstName = request.POST.get("FirstName")
        LastName = request.POST.get("LastName")
        password = request.POST.get("password")
        Email = request.POST.get("Email")
        country = request.POST.get("country")
        state = request.POST.get("state")
        city = request.POST.get("city")
        pincode = request.POST.get("pincode")
        auth = signup.objects.filter(Email=Email).count()
        if auth > 0:
            message = "User 2 Already Register"
            return render(request, "registration/register.html", {'message': message})
        else:
            signup(FirstName=FirstName, LastName=LastName, password=password, Email=Email, country=country, state=state,
                   city=city, pincode=pincode).save()
        return render(request, "registration/login.html")
    else:
        return render(request, "registration/login.html")


def loginUser(request):
    if request.method== "POST":
        UserEmail = request.POST.get("Email")
        password = request.POST.get("password")
        count = signup.objects.filter(Email=UserEmail, password=password)
        if count.count()>0:
            request.session['UserEmail'] = UserEmail
            return redirect('/', {'UserEmail': UserEmail})

        else:
            message = "invalid user or password"
            return render(request, "registration/login.html", {'message': message})
    else:
        return HttpResponse("invalid POST REQUEST")


def logout(request):
    request.session.flush()
    return redirect("/")

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/blog.css' %}" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
  <!-- <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">  -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,100&display=swap" rel="stylesheet">    
  <link href={% static "css/fontawesome-free-5.15.3-web/css/all.css" %} rel="stylesheet">
  
  
</head>

<body>
  <nav class="p-3 mb-2 navbar navbar-expand-lg navbar-dark fixed-top  border border-dark" style="background-color: #000000;">
    <a class="navbar-brand" href="#">Ketan Parihar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto navbar-light">
        <a class="nav-link active " href={% url "blog:home" %}>Home <span class="sr-only">(current)</span></a>
        <a class="nav-link" href={% url "blog:post_list" %}>Blog</a>
        <a class="nav-link" href={% url "blog:post_list" %}>About</a>
        <a class="nav-link" href="#">Projects</a>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <button class="btn btn-outline-success my-2 my-sm-0 pt-2 m-2" type="button"><a href="/registrationpage/" >Registration</a></button>
           <button class="btn btn-outline-primary my-2 my-sm-0 pt-2 m-2" type="button"><a href="/loginpage/" >Log In</a></button>
           <button class="btn btn-outline-danger my-2 my-sm-0 pt-2 m-2" type="button"><a href="/logout/" >Log Out</a></button>
          
        </form>
      </div>
    </div>
  </nav>
</body>
</html>
{% block content %}
{% endblock %}

blog/templates/blog/fotter.html
        <!-- Footer -->
        <footer class="page-footer font-small bg-warning pt-4">

            <!-- Footer Links -->
            <div class="container text-center text-md-left">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

                        <!-- Content -->
                        <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
                        <p>Here you can use rows and columns to organize your footer content.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit amet numquam iure provident
                            voluptate
                            esse
                            quasi, veritatis totam voluptas nostrum.</p>

                    </div>
                    <!-- Grid column -->

                    <hr class="clearfix w-100 d-md-none">

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

                        <!-- Links -->
                        <h5 class="font-weight-bold text-uppercase mb-4">About</h5>

                        <ul class="list-unstyled">
                            <li>
                                <p>
                                    <a href="#!">PROJECTS</a>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#!">ABOUT US</a>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#!">BLOG</a>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#!">AWARDS</a>
                                </p>
                            </li>
                        </ul>

                    </div>
                    <!-- Grid column -->

                    <hr class="clearfix w-100 d-md-none">

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

                        <!-- Contact details -->
                        <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>

                        <ul class="list-unstyled">
                            <li>
                                <p>
                                    <i class="fas fa-home mr-3"></i> New York, NY 10012, US
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="fas fa-envelope mr-3"></i> info@example.com
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="fas fa-phone mr-3"></i> + 01 234 567 88
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="fas fa-print mr-3"></i> + 01 234 567 89
                                </p>
                            </li>
                        </ul>

                    </div>
                    <!-- Grid column -->

                    <hr class="clearfix w-100 d-md-none">

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 text-center mx-auto my-4">

                        <!-- Social buttons -->
                        <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>

                        <!-- Facebook -->
                        <a type="button" class="btn-floating btn-fb">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <!-- Twitter -->
                        <a type="button" class="btn-floating btn-tw">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <!-- Google +-->
                        <a type="button" class="btn-floating btn-gplus">
                            <i class="fab fa-google-plus-g"></i>
                        </a>
                        <!-- Dribbble -->
                        <a type="button" class="btn-floating btn-dribbble">
                            <i class="fab fa-dribbble"></i>
                        </a>

                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->

            </div>
            <!-- Footer Links -->

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">© 2020 Copyright:
                <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<br><br><br><br>
<div class="container bg-light pb-5">
    <h1>{{ post.title }}</h1>
    <p class="date">
       published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
      <a href="{% url "blog:post_share" post.id %}">share this post</a>
    </p>

    {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment {{ total_comments|pluralize }}
        </h2>
    {% endwith %}

   <!--comment in our blog ---->

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                comment {{ forloop.counter }} by {{ comment.name }}{{ comment.created }}
            </p>

            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comment yet</p>
    {% endfor %}

    <!--new comment in our blog ---->

    {% if new_comment %}
        <h2>your comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
             {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %} My Blog {% endblock %}

{% block content %}
<br>
<br>
<div class="container pt-5">
    <div class="jumbotron">
        <h1 align="center"> <b>Ketan parihar</b></h1>
    </div>
</div>

<div class="container pb-5 bg-light">
    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="date">
        published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks}}
    {% endfor %}

    {% include "pagination.html" with page=page_obj %}
</div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}

share a post
{% endblock %}

{% block content %}
<div class="container mb-5 mt-5 pt-5 bg-dark">
    {% if sent %}
        <h1>Email sucessfully send</h1>
        <p>
           "{{ post.title }}" was sucessfully send to  {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
             {{ form.as_p }}
              {% csrf_token %}
              <input type="submit" value="send e-mail">
        </form>
    {% endif %}
</div>

{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}

        <a href="?page={{ page.previous_page_number }}">previous</a>

        {% endif %}

        <span class="current">

            Page {{ page.number }} or {{ page.paginator.num_pages }}

        </span>

        {% if page.has_next %}

        <a href="?page={{ page.next_page_number }}">Next</a>

        {% endif %}
    </span>
</div>